Unitarity enforcement option for intermediate condition.
LLNL/quandary pull request #20
Opened 2024-01-25 01:35 UTC by dreamer2368

- The unitarity of intermediate conditions can be enforced by specifying the input `optim_unitarize_interm_ic=true`.
- This currently performs modified Gram-Schmidt operation on all processes, which needs parallelization in future.

2024-01-26 00:35 UTC, andersp requested changes
Your code looks fine, but I don't understand why the discontinuity reported after rollout becomes non-zero. This happens, e.g., in the case results/gate_swap02/swap02.cfg when optim_unitarize_interm_ic=true. Setting that variable to false gives zero rollout discontinuities, as expected.

2024-01-26 01:46 UTC, dreamer2368 commented
> Your code looks fine, but I don't understand why the discontinuity reported after rollout becomes non-zero. This happens, e.g., in the case results/gate_swap02/swap02.cfg when optim_unitarize_interm_ic=true. Setting that variable to false gives zero rollout discontinuities, as expected.

Added a commit to fix the rollout result.

2024-01-26 21:29 UTC, andersp commented on include/optimproblem.hpp
Better to keep this variable private and add an access function if you need to change it for rollOut(), which by the way, is not needed anymore

2024-01-26 21:31 UTC, andersp commented on src/main.cpp
Is there any need to turn off the projection for rollout after unitarize() was corrected?

2024-01-26 21:36 UTC, andersp commented on src/util.cpp
The standard way of defining the scalar product for complex vectors is <x,y> = conj(x)^T * y. This results in the opposite sign for the imaginary part. It would be less confusing if you could follow the standard convention.

2024-01-26 21:38 UTC, andersp commented on src/util.cpp
With the standard definition of the scalar product, you would need to reverse the signs of vu_im here.

2024-01-26 21:39 UTC, andersp commented on src/util.cpp
Same change as in the previous comment

2024-01-26 21:40 UTC, andersp commented on src/util.cpp
Here too :-)

2024-01-29 18:22 UTC, dreamer2368 commented on src/main.cpp
`OptimProblem::rollOut` never uses intermediate conditions and therefore no projection. `OptimProblem::evalF` after that requires turning off the projection.

2024-01-29 18:28 UTC, andersp commented on src/main.cpp
My point is that the projection doesn't change the state if the state is already unitary.

2024-02-02 02:39 UTC, dreamer2368 commented on src/util.cpp
Followed your convention and changed the operations accordingly

2024-02-02 02:40 UTC, dreamer2368 commented on src/util.cpp
The convention change is reflected and no need to change the signs outside the inner product routine.

2024-02-02 02:40 UTC, dreamer2368 commented on src/util.cpp
Same as above

2024-02-02 02:40 UTC, dreamer2368 commented on src/util.cpp
Same as above

2024-02-02 02:43 UTC, dreamer2368 commented on src/main.cpp
For `OptimProblem::evalF`, I wouldn't put the unitarity check since it requires computing inner products for all initial conditions.

Ideal way of evaluating the rollout infidelity would be to evaluate it in `OptimProblem::rollOut`, not running the simulation one more with `OptimProblem::evalF`. In such case we do not need the unitarity check.

2024-02-02 02:46 UTC, dreamer2368 commented on include/optimproblem.hpp
Ideal way of evaluating the rollout infidelity would be to evaluate it in `OptimProblem::rollOut`, not running the simulation one more with `OptimProblem::evalF`. In such case we do not need `unitarize_interm_ic` to be public, nor we need an access function to it.

2024-02-02 02:52 UTC, dreamer2368 commented
Three main changes are added:
- inner product convention is changed and reflected throught all unitarization routines.
- Some necessary memory clean-up routines are called in order to avoid memory leak.
- In the beginning I thought I implemented classic GS, but it turns out to be the modified one. The gradient is formulated with respect to the classic one, which costs less memory and has the equivalent gradient. In this commit, the unitarization routine reflects the conventional loop order of the modified GS.

2024-02-03 18:54 UTC, andersp submitted a review, later dismissed
Thanks for your updates!

2024-02-22 19:08 UTC, merged